name: Daily Job Email (India Fresher)

on:
  schedule:
    - cron: "30 15 * * *"   # runs at 9 PM IST
  workflow_dispatch:

jobs:
  job-search:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          pip install requests beautifulsoup4

      - name: Run Job Bot
        run: python job_bot.py
        env:
          EMAIL_USER: ${{ secrets.EMAIL_USER }}
          EMAIL_PASS: ${{ secrets.EMAIL_PASS }}

          
